server:
  port : 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  h2:
    console:
      enabled:true

  datasource:
    url: jdbc:h2:tcp://localhost/~/auction
    username: sa
    password :
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ## show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug