server:
  port : 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  h2:
    console:
      enabled:true
  servlet:
    multipart:
      max-file-size : 100MB
      max-request-size : 100MB

  datasource:
    url: jdbc:h2:tcp://localhost/~/auction
    username: sa
    password :
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        ## show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug